# Generated by Django 5.1.4 on 2025-12-01 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('name', models.CharField(max_length=100, verbose_name='API Key 이름')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='API Key')),
                ('prefix', models.CharField(max_length=8, verbose_name='Key Prefix')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 사용일시')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료일시')),
                ('can_read', models.BooleanField(default=True, verbose_name='읽기 권한')),
                ('can_write', models.BooleanField(default=False, verbose_name='쓰기 권한')),
                ('can_delete', models.BooleanField(default=False, verbose_name='삭제 권한')),
                ('rate_limit', models.IntegerField(default=1000, verbose_name='시간당 요청 제한')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
